/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 08-Jul-2010, 11:47:44
 */

/**
 *
 * @author Laa
 */
import java.util.*;
import java.sql.*;

public class MainFrame extends javax.swing.JFrame {
        HashMap ar=new HashMap();
        int y=1;
        HashMap uranswer=new HashMap();
        int correct=0;
        int wrong=0;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        LoadQ();
        Toggle(y);

    }

/**
 * **This method is used to load the questions from database into a collection
 */
    public void LoadQ()
    {
    try{
            System.out.println("welcome to view details connection");
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            java.sql.Connection con= DriverManager.getConnection("jdbc:odbc:MyExam");
            PreparedStatement smt1=con.prepareStatement("select * from question order by NEWID()");
            ResultSet rs=smt1.executeQuery();

            ResultSetMetaData rsmd = rs.getMetaData();
            int y=0;
            while (rs.next())
            {
                Question q=new Question();
                q.Questionnumber=rs.getString("qn");
                q.mQuestion=rs.getString("mq");
                q.OptionOne=rs.getString("o1");
                q.OptionTwo=rs.getString("o2");
                q.OptionThree=rs.getString("o3");
                q.OptionFour=rs.getString("o4");
                q.OptionFive=rs.getString("o5");
                q.Answer=rs.getString("answer");
                ar.put(++y, q);
            }

        }catch (SQLException sqle){System.out.println(sqle);} catch (Exception e){

            System.out.println(e);
        }

    
    }



    /** This method is called from within the constructor to
     * it is used ro kick start the collection that holds the data and it will be used toggle between questions
     *
     */
    public void Toggle(int y)
    {
    buttonGroup1.clearSelection();

      
        if(y<=7)
        {
           Question q=(Question)ar.get(y);

//        qn.setText(q.Questionnumber);
        Integer ww=new Integer(y);
        qn.setText(ww.toString());
        mq.setText(q.mQuestion);
        o1.setText(q.OptionOne);
        o2.setText(q.OptionTwo);
        o3.setText(q.OptionThree);
        o4.setText(q.OptionFour);
        o5.setText(q.OptionFive);
       return;
        }else
        {
        int w=7;
        y=--w;
        System.out.println(uranswer.get(1));
        System.out.println(uranswer.get(2));
        System.out.println(uranswer.get(3));
        System.out.println(uranswer.get(4));
        System.out.println(uranswer.get(5));
        }
    }

    
    /** This method is called from within the constructor to
     * it is used to toggle between questions backwards
     *
     */
        public void ToggleBackward(int y)
    {

        
        while(y>=1 && y<=7)
        {

        Question q=(Question)ar.get(y);
        Integer ww=new Integer(y);
        qn.setText(ww.toString());
        mq.setText(q.mQuestion);
        o1.setText(q.OptionOne);
        o2.setText(q.OptionTwo);
        o3.setText(q.OptionThree);
        o4.setText(q.OptionFour);
        o5.setText(q.OptionFive);
        return;
        }
        ++y;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        o1 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        o2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        o3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rb3 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        o5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rb5 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        o4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mq = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        right = new javax.swing.JLabel();
        wron = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("My Exam!!!!!!");

        jLabel2.setText("Question Number");

        qn.setText("jLabel8");
        qn.setName("qn"); // NOI18N

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("Option One:");

        o1.setText("jLabel10");
        o1.setName("o1"); // NOI18N

        buttonGroup1.add(rb1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(o1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 543, Short.MAX_VALUE)
                .addComponent(rb1)
                .addGap(162, 162, 162))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(o1)
                    .addComponent(rb1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        o2.setText("jLabel10");
        o2.setName("o2"); // NOI18N

        jLabel4.setText("Option Two:");

        buttonGroup1.add(rb2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(o2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 544, Short.MAX_VALUE)
                .addComponent(rb2)
                .addGap(161, 161, 161))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rb2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(o2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        o3.setText("jLabel10");
        o3.setName("o3"); // NOI18N

        jLabel5.setText("Option Three:");

        buttonGroup1.add(rb3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(o3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
                .addComponent(rb3)
                .addGap(161, 161, 161))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb3)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(o3)))
                .addContainerGap())
        );

        o5.setText("jLabel10");
        o5.setName("o5"); // NOI18N

        jLabel7.setText("Option Five:");

        buttonGroup1.add(rb5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(o5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 511, Short.MAX_VALUE)
                .addComponent(rb5)
                .addGap(147, 147, 147))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rb5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(o5)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        o4.setText("jLabel10");
        o4.setName("o4"); // NOI18N

        jLabel6.setText("Option Four:");

        buttonGroup1.add(rb4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(o4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 548, Short.MAX_VALUE)
                .addComponent(rb4)
                .addGap(159, 159, 159))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb4)
                    .addComponent(o4))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mq.setColumns(20);
        mq.setLineWrap(true);
        mq.setRows(5);
        mq.setText(".");
        jScrollPane1.setViewportView(mq);

        jButton3.setText("End Exam");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        right.setForeground(new java.awt.Color(0, 255, 0));

        wron.setBackground(new java.awt.Color(240, 0, 0));
        wron.setForeground(new java.awt.Color(250, 5, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(qn)
                        .addGap(254, 254, 254)
                        .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wron, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(qn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wron, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-824)/2, (screenSize.height-600)/2, 824, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(y<=10)
        {

         Question q;
        if(y>10)
        {
        q=(Question)ar.get(10);

        }
        else{q=(Question)ar.get(y);}
        javax.swing.ButtonModel bm=buttonGroup1.getSelection();

           if(rb1.isSelected())
            {
            uranswer.put(y,q.OptionOne+",OptionOne");
            }
            else if(rb2.isSelected())
            {
            uranswer.put(y,q.OptionTwo+",OptionTwo");
            }
            else if(rb3.isSelected())
            {
            uranswer.put(y,q.OptionThree+",OptionThree");
            }
            else if(rb4.isSelected())
            {
            uranswer.put(y,q.OptionFour+",OptionFour");
            }
            else if(rb5.isSelected())
            {
            uranswer.put(y,q.OptionFive+",OptionFive");
            }


        Toggle(++y);
        //trying to make it work for also moving forward after the first as in for review
        String t=(String)uranswer.get(y);
        if(t!=null)
        {
          int as=t.indexOf(",", 0);
          //  System.out.println(as);
          String store=t.substring(++as, t.length());
          //System.out.println(store);

          if(store.equals("OptionOne"))
          {
            rb1.setSelected(true);
          }
          else if(store.equals("OptionTwo"))
          {
            rb2.setSelected(true);
          }
          else if(store.equals("OptionThree"))
          {
              rb3.setSelected(true);
          }
          else if(store.equals("OptionFour"))
          {
              rb4.setSelected(true);
          }
          else if(store.equals("OptionFive"))
          {
              rb5.setSelected(true);
          }
        }
        else{buttonGroup1.clearSelection();}
        //end of review test ends here



        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(y>1)
        ToggleBackward(--y);
        String q=(String)uranswer.get(y);
        if(q!=null)
        {
            int as=q.indexOf(",", 0);
          //  System.out.println(as);
          String store=q.substring(++as, q.length());
          //System.out.println(store);

          if(store.equals("OptionOne"))
          {
            rb1.setSelected(true);
          }
          else if(store.equals("OptionTwo"))
          {
            rb2.setSelected(true);
          }
          else if(store.equals("OptionThree"))
          {
              rb3.setSelected(true);
          }
          else if(store.equals("OptionFour"))
          {
              rb4.setSelected(true);
          }
          else if(store.equals("OptionFive"))
          {
              rb5.setSelected(true);
          }
        }
        else{buttonGroup1.clearSelection();}
    }//GEN-LAST:event_jButton2ActionPerformed



    /****
     **This is Aimed at trying to mark the scores of the student
     **just trying to use the same collection object that holds the question
     **good
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        rb1.setEnabled(false);
        rb2.setEnabled(false);
        rb3.setEnabled(false);
        rb4.setEnabled(false);
        rb5.setEnabled(false);
        
        for(int i=1;i<7;i++)
        {
        Question q=(Question)ar.get(i);
        String s=q.Answer;
        String t=(String)uranswer.get(i);
        int as=t.indexOf(",");
        String store=t.substring(0, as);
        System.out.println(store);
            if(store.equals(s))
            {
               correct++;

            }
            else
            {
               wrong++;
            }
        
        }
        wron.setText(new Integer(wrong).toString());
        right.setText(new Integer(correct).toString());
       jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mq;
    private javax.swing.JLabel o1;
    private javax.swing.JLabel o2;
    private javax.swing.JLabel o3;
    private javax.swing.JLabel o4;
    private javax.swing.JLabel o5;
    private javax.swing.JLabel qn;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JLabel right;
    private javax.swing.JLabel wron;
    // End of variables declaration//GEN-END:variables

}
